name: comp4768_mun_thrift
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1

  # state management
  flutter_riverpod: ^2.5.1  

  # routing
  go_router: ^14.1.4      

  # local db
  hive: ^2.2.3            
  hive_flutter: ^1.1.0    
  
  # hive code generation for custom objects
  hive_generator: ^2.0.1   
  
  # riverpod code generation
  riverpod_annotation: ^2.3.5 

  # UI
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.11     
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

